---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  tidy.opts = list(width.cutoff = 80),
  tidy = TRUE
)
```

# SIGNAL UMAP 

Post-assembly consensus fasta sequence clustering of SARS-CoV-2 viral isolates with respect to GISAID data.

## Overview

All post-assembly consensus fastas can be appended to one `fasta` file, and along with a `.txt` file containing newline separated locations of the viral isolate (should be country or more fine-grained), can be analyzed in parallel (**see example files**). New folders corresponding to the sequences will be created in the `data` folder, with naming convention `Seq_n_[fasta_header]`. Two umap plots will be created - one with region of origin `Seq_n_[fasta_header]_umap_region.pdf` and one with country of origin (zoomed in) `Seq_n_[fasta_header]_umap_country_zoom.pdf`. The level of zoom can be set (**2.5-5** is best - this corresponds to upper and lower bound of UMAP coordinates around input sequence). A tsv file containing the metadata for the "zoomed in" cluster and corresponding GISAID sequences is also output `Seq_n_[fasta_header]_umap_data.tsv`. This tsv file contains UMAP coordinates, country and region of origin, and travel history associated with GISAID accessions nearby the input sequence. 

The script options are the following (**see example files**):
```
Rscript --verbose umap.R [input_fasta] [location_txt] [cores] [zoom_level] [length_cutoff] [ambg_nucleotide_cutoff]
```
* input_fasta: location of the input fasta file containing query sequences [file]
* location_txt: location of the matched metadata txt file containing sampling location of the query sequences [file]
* cores: number of cores to utilize during processing [1-n]
* zoom_level: "radius" of square around query sequence, in UMAP dimension 1 and 2 units [0-100]
* length_cutoff: minimum length of query sequences for filtering [0-30000]
* ambg_nucleotide_cutoff: maximum percentage of ambiguous nucleotides in query sequences for filtering [0-1]

E.g:
```
Rscript --verbose umap.R example_data/example.fasta example_data/example_hist.txt 4 2.5 29000 0.05
```
## Installation

Clone repository:
```
git clone https://github.com/hsmaan/signal_umap.git
```

Get GISAID data from Google API:
```
sh gisaid_data_setup.sh
```

Set up and activate conda environment:
```
conda env create --name umap_env --file umap.yaml
conda activate umap_env
```

Run with example data:
```
Rscript --verbose umap.R example_data/example.fasta example_data/example_hist.txt 4 2.5 29000 0.05 > umap.log 2>&1
```
